databases:
  - name: vocabtrack-db
    plan: free
    region: ohio
    postgresMajorVersion: '18'

services:
  - name: vocabtrack-backend
    type: web
    plan: free
    repo: https://github.com/Linxin-Zhong/Vocab-Track.git
    branch: main
    region: ohio
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python -m uvicorn api.asgi:application --host 0.0.0.0 --port $PORT
    autoDeployTrigger: off
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: vocabtrack-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - name: vocabtrack
    type: web
    repo: https://github.com/Linxin-Zhong/Vocab-Track.git
    branch: main
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeployTrigger: off
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: vocabtrack-backend
          envVarKey: RENDER_EXTERNAL_URL
