# Generated by Django 6.0.1 on 2026-03-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_rename_username_user_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_book_id',
            field=models.IntegerField(blank=True, db_column='selected_book_id', null=True),
        ),
    ]
