# Generated by Django 6.0.1 on 2026-02-03 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='book_id', primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_book',
            },
        ),
        migrations.CreateModel(
            name='BookWord',
            fields=[
                ('id', models.AutoField(db_column='book_word_id', primary_key=True, serialize=False)),
                ('meaning', models.CharField(max_length=255)),
                ('example', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('word_id', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
            options={
                'db_table': 'tbl_book_word',
                'constraints': [models.UniqueConstraint(fields=('book_id', 'word_id'), name='unique_book_word')],
            },
        ),
    ]
