# Generated by Django 6.0.1 on 2026-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookword',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookword',
            old_name='word_id',
            new_name='word',
        ),
        migrations.AlterConstraint(
            model_name='bookword',
            name='unique_book_word',
            constraint=models.UniqueConstraint(fields=('book', 'word'), name='unique_book_word'),
        ),
    ]
