# Generated by Django 6.0.1 on 2026-02-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_id_bookword_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
