# Generated by Django 6.0.1 on 2026-02-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(db_column='word_id', primary_key=True, serialize=False)),
                ('word_text', models.CharField(db_column='word_text', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_word',
            },
        ),
    ]
