# Generated by Django 6.0.1 on 2026-02-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0003_rename_user_id_book_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.AutoField(db_column='rw_session_id', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_cnt', models.IntegerField(default=0)),
                ('correct_cnt', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_session', to='book.book')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_review_session',
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(db_column='user_word_id', primary_key=True, serialize=False)),
                ('ease_factor', models.IntegerField(default=0)),
                ('correct_times', models.IntegerField(default=0)),
                ('wrong_times', models.IntegerField(default=0)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('next_review_time', models.DateTimeField(blank=True, null=True)),
                ('book_word', models.ForeignKey(db_column='book_word_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='book.bookword')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_word',
                'unique_together': {('user', 'book_word')},
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.AutoField(db_column='rw_item_id', primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('pre_ease_factor', models.IntegerField()),
                ('post_ease_factor', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='rw_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_item', to='review.reviewsession')),
                ('user_word', models.ForeignKey(db_column='user_word_id', on_delete=django.db.models.deletion.CASCADE, related_name='review_item', to='review.userword')),
            ],
            options={
                'db_table': 'tbl_review_item',
            },
        ),
    ]
