# Generated by Django 6.0.1 on 2026-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(fields=('session', 'user_word'), name='uniq_review_item_session_user_word'),
        ),
    ]
